site_name: podcasts
site_description: Its all about a Weissman score > 5.0
repo_url: https://github.com/saylau/podcasts
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/saylau">saylau</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
